version: "3"

volumes:
  db-data:
    external: false

services:
  rails_school_website_db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    image: postgres:latest
    volumes:
      - db-data:/usr/local/psql/data
  rails_school_website_app:
    #env_file: .env
    build:
      context: .
      dockerfile: rails_school_website_app.Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    command: bash -c "cd /usr/src/app && rm -f tmp/pids/server.pid && set RAILS_ENV=production && rake secret && rails db:setup && bundle exec unicorn_rails -p 3000 -E development"
    ports:
      - "3000:3000"
    depends_on:
      - rails_school_website_db
  rails_school_website_nginx:
    build:
      context: .
      dockerfile: rails_school_website_nginx.Dockerfile
    depends_on:
      - rails_school_website_app
    ports:
      - 80:80
