version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    image: postgres:latest
    volumes:
      - db-data:/usr/local/psql/data
  app:
    #env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    command: bash -c "cd /usr/src/app && rm -f tmp/pids/server.pid && rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
